version: '3'

services:
 db:
    build: ./local_run
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: library_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
 web:
    build:
     context: .
     dockerfile: Dockerfile-local
    command: python3 manage.py migrate
    # command: gunicorn -c=gunicorn_config.py ip_service.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    links:
     - db:library_db
