# Generated by Django 2.1.7 on 2019-02-28 18:19

from django.db import migrations, models
import django.db.models.deletion
import main_room.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_published", models.DateField()),
                ("title", models.CharField(max_length=245)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "DRAFT"),
                            (1, "PUBLISHED"),
                            (2, "DENIED"),
                            (3, "CANCELLED"),
                        ],
                        null=True,
                    ),
                ),
                ("barcode", main_room.models.Binary365Field(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=45)),
                ("birth_date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="books",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main_room.Writer"
            ),
        ),
    ]
